# Generated by Django 5.2 on 2025-12-17 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0024_compra_direccion_envio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_confirmacion_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='recibido_por_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_camino', 'En camino'), ('enviado', 'Enviado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='EntregaDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_recorrido', models.DateTimeField(blank=True, null=True)),
                ('fin_recorrido', models.DateTimeField(blank=True, null=True)),
                ('entregado', models.BooleanField(default=False)),
                ('motivo_no_entrega', models.TextField(blank=True, null=True)),
                ('intentos_entrega', models.IntegerField(default=0)),
                ('reintentar', models.BooleanField(default=False)),
                ('compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='MainApp.compra')),
            ],
            options={
                'verbose_name': 'Entrega a Domicilio',
                'verbose_name_plural': 'Entregas a Domicilio',
            },
        ),
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=255)),
                ('detalle', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Cambio',
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['-fecha'],
            },
        ),
    ]
