# Generated by Django 5.2 on 2025-12-17 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0025_compra_fecha_confirmacion_recepcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcambios',
            name='usuario',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='recibido_por_cliente',
            new_name='confirmado_por_cliente',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fecha_confirmacion_recepcion',
        ),
        migrations.AddField(
            model_name='compra',
            name='delivery_finalizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='delivery_iniciado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_confirmacion_cliente',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='intentos_entrega',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compra',
            name='motivo_no_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('no_entregado', 'No entregado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='HistorialAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('venta_manual', 'Venta Manual'), ('inicio_delivery', 'Inicio Delivery'), ('fin_delivery', 'Fin Delivery'), ('cambio_estado', 'Cambio Estado')], max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Administración',
                'verbose_name_plural': 'Historiales de Administración',
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='EntregaDomicilio',
        ),
        migrations.DeleteModel(
            name='HistorialCambios',
        ),
    ]
