# Generated by Django 5.2 on 2025-12-17 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0026_remove_historialcambios_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_recorrido', models.DateTimeField(blank=True, null=True)),
                ('fin_recorrido', models.DateTimeField(blank=True, null=True)),
                ('intentos_entrega', models.IntegerField(default=0)),
                ('entregado', models.BooleanField(default=False)),
                ('motivo_no_entrega', models.TextField(blank=True, null=True)),
                ('compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega_domicilio', to='MainApp.compra')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=255)),
                ('detalle', models.TextField()),
                ('tipo', models.CharField(choices=[('producto', 'Producto'), ('venta', 'Venta'), ('entrega', 'Entrega'), ('eliminacion', 'Eliminación'), ('categoria', 'Categoría'), ('bodega', 'Bodega'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
